spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://idp:9999/auth/realms/one
  data:
    mongodb:
      autoIndexCreation: false # for demo purposes

server:
  port: 8081
